"""Génère latex/numbers_en.tex depuis latex/numbers.tex.

Conversion mécanique de la virgule décimale française vers le point
décimal anglais dans le corps de chaque macro \\newcommand{...}{...}.
Les valeurs numériques ne sont pas modifiées, seul le séparateur l'est.
Ne traite pas les macros sans virgule (entiers, expressions type "p = 1").

Usage : python3 scripts/make_numbers_en.py
"""

import re
from pathlib import Path

LATEX_DIR = Path(__file__).resolve().parent.parent / "latex"
SOURCE = LATEX_DIR / "numbers.tex"
TARGET = LATEX_DIR / "numbers_en.tex"

DECIMAL_COMMA = re.compile(r"(\\newcommand\{\\\w+\}\{-?)(\d+),(\d+)(\})")

HEADER = (
    "% Generated by scripts/make_numbers_en.py from numbers.tex\n"
    "% (decimal comma -> decimal point conversion only; values unchanged).\n"
)


def main() -> None:
    content = SOURCE.read_text(encoding="utf-8")
    converted = DECIMAL_COMMA.sub(lambda m: f"{m.group(1)}{m.group(2)}.{m.group(3)}{m.group(4)}", content)
    TARGET.write_text(HEADER + converted, encoding="utf-8")


if __name__ == "__main__":
    main()
